# Generated by Django 4.2.5 on 2023-09-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('notificacao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racas', to='GrandeOrvalho.especie')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
            },
        ),
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1)),
                ('status', models.CharField(max_length=20)),
                ('tipo_sanguineo', models.CharField(max_length=20)),
                ('cliente', models.ManyToManyField(related_name='animais', to='GrandeOrvalho.cliente')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animais', to='GrandeOrvalho.raca')),
            ],
            options={
                'verbose_name': 'Animais',
                'verbose_name_plural': 'Animais',
            },
        ),
    ]
