# Generated by Django 4.2.5 on 2023-10-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("GrandeOrvalho", "0003_animais_capa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animais",
            name="capa",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="uploader.image"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="animais",
            name="idade",
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
