<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-14 16:39
=======
# Generated by Django 4.2.6 on 2023-10-10 19:42
>>>>>>> da7976f8b5b2ec9046cee4feea53d94f5bd28f99

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GrandeOrvalho", "0004_alter_animais_capa_alter_animais_idade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animais",
            name="idade",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
