# Generated by Django 4.2.6 on 2023-10-14 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("GrandeOrvalho", "0006_tipousuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipousuario",
            name="cliente",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="GrandeOrvalho.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="tipousuario",
            name="funcionario",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="GrandeOrvalho.funcionario"
            ),
        ),
    ]
