# Generated by Django 4.2.6 on 2023-10-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GrandeOrvalho", "0007_alter_tipousuario_cliente_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="email",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="senha",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="email",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="senha",
        ),
        migrations.AddField(
            model_name="cliente",
            name="idade",
            field=models.DecimalField(decimal_places=2, default=18, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="sexo",
            field=models.CharField(choices=[("F", "Feminino"), ("M", "Masculino")], default=18, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="funcionario",
            name="idade",
            field=models.DecimalField(decimal_places=2, default=18, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="funcionario",
            name="sexo",
            field=models.CharField(choices=[("F", "Feminino"), ("M", "Masculino")], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
