# Generated by Django 4.2.6 on 2023-10-24 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GrandeOrvalho", "0009_alter_tipousuario_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TipoUsuario",
        ),
    ]
