# Generated by Django 4.2.6 on 2023-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GrandeOrvalho", "0010_delete_tipousuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="sexo",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="sexo",
        ),
        migrations.AddField(
            model_name="cliente",
            name="genero",
            field=models.IntegerField(choices=[(1, "Homem"), (2, "Mulher"), (3, "Prefiro não comentar")], default=3),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="genero",
            field=models.IntegerField(choices=[(1, "Homem"), (2, "Mulher"), (3, "Prefiro não comentar")], default=3),
        ),
    ]
