# Generated by Django 4.2.6 on 2023-10-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GrandeOrvalho", "0011_remove_cliente_sexo_remove_funcionario_sexo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="genero",
            field=models.IntegerField(
                choices=[(1, "Homem"), (2, "Mulher"), (3, "Prefiro não comentar")], default=3, verbose_name="Gênero"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="genero",
            field=models.IntegerField(
                choices=[(1, "Homem"), (2, "Mulher"), (3, "Prefiro não comentar")], default=3, verbose_name="Gênero"
            ),
        ),
    ]
