# Generated by Django 4.2.6 on 2023-10-27 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0006_usuario_capa_usuario_genero_usuario_idade_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("GrandeOrvalho", "0012_alter_cliente_genero_alter_funcionario_genero"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Funcionario",
        ),
        migrations.RemoveField(
            model_name="animais",
            name="sexo",
        ),
        migrations.AddField(
            model_name="animais",
            name="genero",
            field=models.IntegerField(
                choices=[(1, "Homem"), (2, "Mulher"), (3, "Prefiro não comentar")], default=3, verbose_name="Gênero"
            ),
        ),
        migrations.RemoveField(
            model_name="animais",
            name="cliente",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.AddField(
            model_name="animais",
            name="cliente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animais",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
