# Generated by Django 4.2.6 on 2023-10-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GrandeOrvalho", "0013_delete_funcionario_remove_animais_sexo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animais",
            name="tipo_animal",
            field=models.IntegerField(choices=[(1, "Cachorro"), (2, "Gato")], default=1, verbose_name="Tipo de animal"),
        ),
    ]
