# Generated by Django 4.2.6 on 2023-10-27 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GrandeOrvalho", "0014_animais_tipo_animal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animais",
            name="tipo_animal",
        ),
    ]
