# Generated by Django 4.2.6 on 2023-10-14 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0002_usuario_capa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="capa",
        ),
    ]
