# Generated by Django 4.2.6 on 2023-10-27 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0004_tipousuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tipousuario",
            name="user",
        ),
    ]
