# Generated by Django 4.2.6 on 2023-10-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("usuario", "0005_remove_tipousuario_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="capa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="uploader.image",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="genero",
            field=models.IntegerField(
                choices=[(1, "Homem"), (2, "Mulher"), (3, "Prefiro não comentar")], default=3, verbose_name="Gênero"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="idade",
            field=models.DecimalField(decimal_places=2, default=16, max_digits=10),
        ),
        migrations.AddField(
            model_name="usuario",
            name="nome",
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name="usuario",
            name="notificacao",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="user",
            field=models.IntegerField(
                choices=[(1, "Funcionario"), (2, "Cliente")], default=2, verbose_name="Tipo de Usuário"
            ),
        ),
        migrations.DeleteModel(
            name="TipoUsuario",
        ),
    ]
