# Generated by Django 4.2.6 on 2023-10-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0007_alter_usuario_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="genero",
            field=models.IntegerField(
                choices=[(1, "Homem"), (2, "Mulher"), (3, "Prefiro não comentar")], default=3, verbose_name="Gênero"
            ),
        ),
    ]
